import type {
  Project,
  Module,
  UserStory,
  TestCase,
} from './types'

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Sistema de Gestión de Inventario',
    description: 'Aplicación web para gestionar el inventario de productos de una empresa.',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-20'),
  },
  {
    id: 'proj-2',
    name: 'Portal de Clientes',
    description: 'Portal web para que los clientes puedan gestionar sus pedidos y facturas.',
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'proj-3',
    name: 'App Móvil de Ventas',
    description: 'Aplicación móvil para el equipo de ventas en campo.',
    status: 'archived',
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2023-12-15'),
  },
]

// Mock Modules
export const mockModules: Module[] = [
  {
    id: 'mod-1',
    projectId: 'proj-1',
    name: 'Gestión de Productos',
    description: 'Módulo para crear, editar y eliminar productos del inventario.',
    order: 1,
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'mod-2',
    projectId: 'proj-1',
    name: 'Control de Stock',
    description: 'Módulo para gestionar entradas y salidas de inventario.',
    order: 2,
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'mod-3',
    projectId: 'proj-1',
    name: 'Reportes',
    description: 'Módulo para generar reportes de inventario.',
    order: 3,
    createdAt: new Date('2024-01-16'),
  },
  {
    id: 'mod-4',
    projectId: 'proj-2',
    name: 'Autenticación',
    description: 'Módulo de login y registro de usuarios.',
    order: 1,
    createdAt: new Date('2024-02-02'),
  },
  {
    id: 'mod-5',
    projectId: 'proj-2',
    name: 'Pedidos',
    description: 'Gestión de pedidos del cliente.',
    order: 2,
    createdAt: new Date('2024-02-02'),
  },
]

// Mock User Stories
export const mockUserStories: UserStory[] = [
  {
    id: 'us-1',
    projectId: 'proj-1',
    moduleId: 'mod-1',
    code: 'US-001',
    title: 'Crear nuevo producto',
    asA: 'administrador de inventario',
    iWant: 'poder crear nuevos productos en el sistema',
    soThat: 'pueda mantener actualizado el catálogo de productos disponibles',
    status: 'done',
    priority: 'high',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-1', userStoryId: 'us-1', description: 'El formulario debe validar campos obligatorios', order: 1 },
      { id: 'ac-2', userStoryId: 'us-1', description: 'El código del producto debe ser único', order: 2 },
      { id: 'ac-3', userStoryId: 'us-1', description: 'Se debe mostrar mensaje de confirmación al guardar', order: 3 },
    ],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'us-2',
    projectId: 'proj-1',
    moduleId: 'mod-1',
    code: 'US-002',
    title: 'Editar producto existente',
    asA: 'administrador de inventario',
    iWant: 'poder modificar los datos de un producto existente',
    soThat: 'pueda corregir errores o actualizar información',
    status: 'testing',
    priority: 'high',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-4', userStoryId: 'us-2', description: 'Se debe cargar la información actual del producto', order: 1 },
      { id: 'ac-5', userStoryId: 'us-2', description: 'Los cambios deben guardarse correctamente', order: 2 },
    ],
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'us-3',
    projectId: 'proj-1',
    moduleId: 'mod-2',
    code: 'US-003',
    title: 'Registrar entrada de stock',
    asA: 'operador de almacén',
    iWant: 'poder registrar la entrada de productos al inventario',
    soThat: 'el stock se mantenga actualizado con las nuevas adquisiciones',
    status: 'in-progress',
    priority: 'critical',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-6', userStoryId: 'us-3', description: 'Se debe seleccionar el producto de una lista', order: 1 },
      { id: 'ac-7', userStoryId: 'us-3', description: 'Se debe ingresar la cantidad y fecha de entrada', order: 2 },
      { id: 'ac-8', userStoryId: 'us-3', description: 'El stock del producto debe actualizarse automáticamente', order: 3 },
    ],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-18'),
  },
  {
    id: 'us-4',
    projectId: 'proj-1',
    moduleId: 'mod-2',
    code: 'US-004',
    title: 'Registrar salida de stock',
    asA: 'operador de almacén',
    iWant: 'poder registrar la salida de productos del inventario',
    soThat: 'el stock refleje las ventas o transferencias realizadas',
    status: 'backlog',
    priority: 'high',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-9', userStoryId: 'us-4', description: 'No se puede registrar salida si no hay stock suficiente', order: 1 },
      { id: 'ac-10', userStoryId: 'us-4', description: 'Se debe registrar el motivo de la salida', order: 2 },
    ],
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: 'us-5',
    projectId: 'proj-1',
    moduleId: 'mod-3',
    code: 'US-005',
    title: 'Generar reporte de inventario',
    asA: 'gerente de operaciones',
    iWant: 'poder generar un reporte del estado actual del inventario',
    soThat: 'pueda tomar decisiones informadas sobre compras y ventas',
    status: 'backlog',
    priority: 'medium',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-11', userStoryId: 'us-5', description: 'El reporte debe poder filtrarse por categoría', order: 1 },
      { id: 'ac-12', userStoryId: 'us-5', description: 'Se debe poder exportar a PDF y Excel', order: 2 },
    ],
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'us-6',
    projectId: 'proj-2',
    moduleId: 'mod-4',
    code: 'US-001',
    title: 'Iniciar sesión',
    asA: 'cliente registrado',
    iWant: 'poder iniciar sesión en el portal',
    soThat: 'pueda acceder a mis pedidos y facturas',
    status: 'done',
    priority: 'critical',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-13', userStoryId: 'us-6', description: 'Se debe validar email y contraseña', order: 1 },
      { id: 'ac-14', userStoryId: 'us-6', description: 'Mostrar mensaje de error si las credenciales son incorrectas', order: 2 },
    ],
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'us-7',
    projectId: 'proj-2',
    moduleId: 'mod-5',
    code: 'US-002',
    title: 'Ver historial de pedidos',
    asA: 'cliente',
    iWant: 'poder ver el historial de mis pedidos anteriores',
    soThat: 'pueda hacer seguimiento de mis compras',
    status: 'in-progress',
    priority: 'high',
    assignedTo: null,
    acceptanceCriteria: [
      { id: 'ac-15', userStoryId: 'us-7', description: 'Mostrar lista de pedidos ordenados por fecha', order: 1 },
      { id: 'ac-16', userStoryId: 'us-7', description: 'Permitir filtrar por estado del pedido', order: 2 },
    ],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-10'),
  },
]

// Mock Test Cases
export const mockTestCases: TestCase[] = [
  {
    id: 'tc-1',
    projectId: 'proj-1',
    userStoryId: 'us-1',
    code: 'TC-001',
    title: 'Crear producto con datos válidos',
    preconditions: 'Usuario autenticado como administrador. Sistema en página de productos.',
    given: 'el usuario está en el formulario de nuevo producto',
    when: 'completa todos los campos requeridos y hace clic en Guardar',
    then: 'el producto se crea exitosamente y aparece en la lista',
    status: 'passed',
    priority: 'high',
    executedAt: new Date('2024-03-05'),
    executedBy: 'María García',
    notes: 'Prueba exitosa en ambiente de desarrollo.',
    assignedTo: null,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'tc-2',
    projectId: 'proj-1',
    userStoryId: 'us-1',
    code: 'TC-002',
    title: 'Validar código de producto único',
    preconditions: 'Existe un producto con código "PROD-001".',
    given: 'el usuario está creando un nuevo producto',
    when: 'ingresa el código "PROD-001" que ya existe',
    then: 'el sistema muestra un error indicando que el código ya está en uso',
    status: 'passed',
    priority: 'high',
    executedAt: new Date('2024-03-05'),
    executedBy: 'María García',
    notes: '',
    assignedTo: null,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'tc-3',
    projectId: 'proj-1',
    userStoryId: 'us-1',
    code: 'TC-003',
    title: 'Validar campos obligatorios',
    preconditions: 'Usuario en formulario de nuevo producto.',
    given: 'el usuario está en el formulario de nuevo producto',
    when: 'intenta guardar sin completar campos obligatorios',
    then: 'el sistema muestra mensajes de validación para cada campo faltante',
    status: 'passed',
    priority: 'medium',
    executedAt: new Date('2024-03-06'),
    executedBy: 'Carlos López',
    notes: '',
    assignedTo: null,
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-03-06'),
  },
  {
    id: 'tc-4',
    projectId: 'proj-1',
    userStoryId: 'us-2',
    code: 'TC-004',
    title: 'Editar producto existente',
    preconditions: 'Existe al menos un producto en el sistema.',
    given: 'el usuario selecciona un producto para editar',
    when: 'modifica el nombre y guarda los cambios',
    then: 'el nombre del producto se actualiza correctamente',
    status: 'pending',
    priority: 'high',
    executedAt: null,
    executedBy: null,
    notes: '',
    assignedTo: null,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'tc-5',
    projectId: 'proj-1',
    userStoryId: 'us-2',
    code: 'TC-005',
    title: 'Cargar datos al editar',
    preconditions: 'Existe un producto con datos completos.',
    given: 'el usuario hace clic en editar un producto',
    when: 'se abre el formulario de edición',
    then: 'todos los campos muestran los valores actuales del producto',
    status: 'failed',
    priority: 'high',
    executedAt: new Date('2024-03-15'),
    executedBy: 'Carlos López',
    notes: 'El campo de descripción no carga correctamente. Bug reportado.',
    assignedTo: null,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'tc-6',
    projectId: 'proj-1',
    userStoryId: 'us-3',
    code: 'TC-006',
    title: 'Registrar entrada de stock válida',
    preconditions: 'Producto existente con stock inicial de 100 unidades.',
    given: 'el usuario está en el formulario de entrada de stock',
    when: 'selecciona un producto e ingresa cantidad de 50 unidades',
    then: 'el stock del producto aumenta a 150 unidades',
    status: 'pending',
    priority: 'high',
    executedAt: null,
    executedBy: null,
    notes: '',
    assignedTo: null,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'tc-7',
    projectId: 'proj-2',
    userStoryId: 'us-6',
    code: 'TC-001',
    title: 'Login exitoso',
    preconditions: 'Usuario registrado con email test@example.com.',
    given: 'el usuario está en la página de login',
    when: 'ingresa credenciales válidas y hace clic en Iniciar Sesión',
    then: 'el usuario es redirigido al dashboard',
    status: 'passed',
    priority: 'high',
    executedAt: new Date('2024-02-28'),
    executedBy: 'Ana Martínez',
    notes: '',
    assignedTo: null,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'tc-8',
    projectId: 'proj-2',
    userStoryId: 'us-6',
    code: 'TC-002',
    title: 'Login con credenciales inválidas',
    preconditions: 'Ninguna.',
    given: 'el usuario está en la página de login',
    when: 'ingresa una contraseña incorrecta',
    then: 'el sistema muestra mensaje de error y no permite el acceso',
    status: 'passed',
    priority: 'high',
    executedAt: new Date('2024-02-28'),
    executedBy: 'Ana Martínez',
    notes: '',
    assignedTo: null,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-28'),
  },
]
